// Code generated by MockGen. DO NOT EDIT.
// Source: services/ping_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockpingServiceInterface is a mock of pingServiceInterface interface
type MockpingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockpingServiceInterfaceMockRecorder
}

// MockpingServiceInterfaceMockRecorder is the mock recorder for MockpingServiceInterface
type MockpingServiceInterfaceMockRecorder struct {
	mock *MockpingServiceInterface
}

// NewMockpingServiceInterface creates a new mock instance
func NewMockpingServiceInterface(ctrl *gomock.Controller) *MockpingServiceInterface {
	mock := &MockpingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockpingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockpingServiceInterface) EXPECT() *MockpingServiceInterfaceMockRecorder {
	return m.recorder
}

// PingService mocks base method
func (m *MockpingServiceInterface) PingService() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingService")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PingService indicates an expected call of PingService
func (mr *MockpingServiceInterfaceMockRecorder) PingService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingService", reflect.TypeOf((*MockpingServiceInterface)(nil).PingService))
}
